%YAML 1.2
---
root: true
env:
  browser: true
  node: true
  commonjs: true
  es2024: true
  jest: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
plugins:
  - prettier
rules:
  camelcase:
    - error
    - properties: never
  comma-dangle:
    - error
    - never
  comma-spacing:
    - error
    - after: true
      before: false
  curly:
    - error
    - all
  dot-notation: error
  eol-last:
    - error
    - always
  eqeqeq:
    - error
    - always
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  multiline-comment-style:
    - error
    - starred-block
  no-alert: error
  no-console: error
  no-extra-semi: error
  no-inline-comments: error
  no-lonely-if: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 0
  no-trailing-spaces: error
  no-unused-vars:
    - error
    - args: all
      argsIgnorePattern: ^_
  no-useless-escape: 'off'
  no-var: error
  object-curly-newline:
    - error
    - ObjectPattern:
        consistent: true
  object-shorthand:
    - error
    - properties
  one-var:
    - error
    - let: consecutive
  prefer-const: error
  prefer-object-has-own: error
  prettier/prettier:
    - warn
    - arrowParens: avoid
      bracketSameLine: true
      bracketSpacing: true
      printWidth: 1000
      semi: true
      singleQuote: true
      tabWidth: 2
      trailingComma: none
      useTabs: false
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
      avoidEscape: true
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: always
      asyncArrow: always
      named: never
  strict:
    - error
    - global
...